// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NugetCollector.Data;

namespace NugetCollector.Data.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20200331142811_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("NugetCollector.Data.Model.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("NugetCollector.Data.Model.ProjectReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceVersion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ReferenceName", "ReferenceVersion");

                    b.ToTable("ProjectReference");
                });

            modelBuilder.Entity("NugetCollector.Data.Model.Reference", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Name", "Version");

                    b.ToTable("References");
                });

            modelBuilder.Entity("NugetCollector.Data.Model.ProjectReference", b =>
                {
                    b.HasOne("NugetCollector.Data.Model.Project", "Project")
                        .WithMany("ProjectReferences")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NugetCollector.Data.Model.Reference", "Reference")
                        .WithMany()
                        .HasForeignKey("ReferenceName", "ReferenceVersion");
                });
#pragma warning restore 612, 618
        }
    }
}
